---

plugins:
  - flowtype
  - jest
  - babel

env:
  node: true
  jest/globals: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'

rules:
  no-console: 0
  no-debugger: 0
  object-curly-newline: 0
  jest/no-disabled-tests: 0
